openapi: 3.0.3
info:
  title: WarframeStat.us API
  description: Simple API for data from the game Warframe.
  contact:
    email: tobiah@protonmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: living
  x-logo:
    url: 'https://warframestat.us/wfcd_logo_color.png'
externalDocs:
  description: Find out more about Warframe
  url: 'https://warframe.com'
servers:
  - url: 'https://api.warframestat.us/'
    description: Production Server
tags:
  - name: Warframe
    description: Everything about Warframe
    externalDocs:
      description: Find out more
      url: 'https://warframe.com'
  - name: Worldstate
    description: Warframe Worldstate Data
    externalDocs:
      description: Find out more
      url: 'https://discord.gg/jGZxH9f'
  - name: GitHub
    description: Review Source Code
    externalDocs:
      description: Check our source code
      url: 'https://github.com/wfcd/warframe-status'
  - name: Unstable
    description: Potentially still in active development
  - name: Searchable
    description: Follows a consistent pattern for searching data
  - name: Rivens
    description: Proxy data for Digital Extreme's semi-regular Riven Data dumps
  - name: Static Processing Data
    description: Direct access via API to the data we use to parse the worldstate
